version: "3.8"

services:
#  gunicorn:
#    container_name: "gunicorn"
#    volumes:
#      - static_volume:/static
#    env_file:
#      - .env
#    build:
#      context: .
#    ports:
#      - "9000:8000"
#    restart: always

  nginx:
    container_name: web
    restart: on-failure
    image: nginx:1.21
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "70:80"
    depends_on:
      - server

  server:
    container_name: backend
    build : .
    env_file: .env
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --reload
    restart: always
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db
    ports:
      - "9000:8000"
      - "5433:5432"

  db:
    container_name: database
    image: mysql
    env_file: database_config/mysql.env
    command: --init-file /data/application/init.sql
    ports:
      - "3308:3306"
    volumes:
      - db_volume:/var/lib/mysql
      - ./database_config/init.sql:/data/application/init.sql

volumes:
  db_volume:
  static_volume:
  media_volume: