version: "3.9"

services:
  nginx:
    container_name: web
    restart: on-failure
    image: nginx:1.21
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
    ports:
      - 80:80
    depends_on:
      - web
  db:
    container_name: database
    command: --init-file /data/application/init.sql
    image: mysql
    restart: always
    env_file:
      - database_config/mysql.env
    ports:
      - '3308:3306'
    volumes:
      - db:/var/lib/mysql
      - ./database_config/init.sql:/data/application/init.sql
  web:
    container_name: server
    build: .
    command: sh -c "python manage.py collectstatic --no-input && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "9000:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: always
volumes:
  static_volume:
  db:
    driver: local