version: "3.9"

services:
  gunicorn:
    container_name: "gunicorn"
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "9000:8000"
    restart: always

  nginx:
    container_name: web
    restart: on-failure
    image: nginx:1.21
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/app/static
      - media:/app/media
    ports:
      - "80:80"
    depends_on:
      - gunicorn

  db:
    container_name: database
    command: --init-file /data/application/init.sql
    image: mysql
    restart: always
    env_file:
      - database_config/mysql.env
    ports:
      - '3308:3306'
    volumes:
      - db:/var/lib/mysql
      - ./database_config/init.sql:/data/application/init.sql
  web:
    container_name: server
    build: .
    volumes:
        - .:/app:rw
        - static:/app/static
        - media:/app/media
    env_file:
      - .env
    depends_on:
      - db
    restart: always
volumes:
  static:
  media:
  db:
    driver: local